// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementApi.Infrastructure.Data;

#nullable disable

namespace TaskManagementApi.Infrastructure.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("TaskManagementApi.Core.Entities.TaskManagementApi.Core.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30e75690-af6b-4273-ada3-b2b4456b2a5b"),
                            CreatedAt = new DateTime(2024, 11, 27, 19, 51, 8, 631, DateTimeKind.Utc).AddTicks(871),
                            Description = "Descripción de la tarea inicial 1",
                            Priority = 0,
                            Status = 0,
                            Title = "Tarea inicial 1",
                            UpdatedAt = new DateTime(2024, 11, 27, 19, 51, 8, 631, DateTimeKind.Utc).AddTicks(871)
                        },
                        new
                        {
                            Id = new Guid("0c9ba1cd-a294-4143-8f60-556564db58a6"),
                            CreatedAt = new DateTime(2024, 11, 27, 19, 51, 8, 631, DateTimeKind.Utc).AddTicks(887),
                            Description = "Descripción de la tarea inicial 2",
                            Priority = 1,
                            Status = 1,
                            Title = "Tarea inicial 2",
                            UpdatedAt = new DateTime(2024, 11, 27, 19, 51, 8, 631, DateTimeKind.Utc).AddTicks(887)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
